site_name: Lambda Kernculus Documentation
repo_url: https://github.com/A-Team-Name/lambda-kernculus

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Overview: index.md
  - Lambda Calculus Parsing: lambda.md
  - Kernel API: main.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - monorepo
  - mkdocstrings
