name: Build, Test and Publish Image

on:
  push:
    branches: [main]

jobs:
  docs_update:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pages: write
    steps:
      - name: Checkout docs code
        uses: actions/checkout@v4
        with:
          repository: A-Team-Name/docs
          token: ${{ secrets.WRITE_TOKEN }}
          submodules: true
      - name: update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Push to main branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Update docs" || echo "No changes to commit"
          git push origin main
          
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        run: echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest
